platform :ios, ‘11.2’
use_frameworks!

def main_pods
    pod 'Alamofire'
    pod 'SwiftLint'
    pod 'R.swift'
end

target 'virtualwallet' do
    main_pods
end

target 'virtualwalletTests' do
    pod 'OHHTTPStubs/Swift'
end

post_install do |installer|
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[‘SWIFT_VERSION’] = ‘4.0’
        end
    end
end
